Main workflow and tests extensions and fixes
lf-edge/eden pull request #474
Opened 2021-01-12 19:42 UTC by sadov

Added USB Passthtrough test and some fixes related to `eve.devmodel` checking. `Eclients` stress test will run now only with non zero EDEN_TEST_APPS env. var.

Signed-off-by: Oleg Sadov <oleg.sadov@gmail.com>

2021-01-15 04:45 UTC, rvs requested changes
The test itself is OK, but I'm concerned that we're now bifurcating the tests into being dependent on what environment they get to be executed in. This one, for example, clearly requires qemu. Before this gets merged I think we need to have a conversation on how we plan to manage these kinds of dependencies.

2021-01-15 09:08 UTC, sadov commented
Sure, it seems ugly for me too. Generally, this check can be moved inside the test. But we need to do some preliminary configuration for QEMU too and restart it. Better to do it once, and now it happens in the overall workflow script. Maybe someone has an idea how best to handle different flavors of EVE platforms in this case.

2021-01-20 08:54 UTC, mydatascience commented
Maybe use just workflow - qemu and this test will work only for this workflow. Rely on devmodel is a bit complicated and definitely need some explanation...

2021-01-20 11:32 UTC, merged

2021-01-22 00:59 UTC, mydatascience commented
@sadov  Need to fix xen on gcp