QEMU: Enable QEMU virtualization on AARCH64
lf-edge/eden pull request #507
Opened 2021-02-02 17:55 UTC by temerkhanov

Enable EVE in QEMU on ARM64

Signed-off-by: Sergey Temerkhanov <s.temerkhanov@gmail.com>

2021-02-02 19:19 UTC, rvs approved these changes
LGTM. @mydatascience @giggsoff -- what do you guys think?

2021-02-02 20:00 UTC, giggsoff requested changes
Please take a look. Now it brokes run on linux with accel.

2021-02-02 20:00 UTC, giggsoff commented on pkg/eden/eden.go
> +				qemuOptions += "-cpu host,invtsc=on,kvmclock=off -machine kernel-irqchip=split"
seems, that you miss space in the end

2021-02-02 20:00 UTC, giggsoff commented on pkg/eden/eden.go
> +		qemuOptions += "-cpu host -machine virt,accel=kvm "
can we split this into with and without acceleration types&

2021-02-02 21:23 UTC, temerkhanov commented
We might need to check it on RPi as well.

2021-02-09 10:36 UTC, mydatascience reviewed
Please fix yetus

2021-02-09 17:30 UTC, rvs commented on pkg/defaults/defaults.go
> +	DefaultQemuAccelLinux  = "-cpu host "
Indeed ;-) @mydatascience 

Not sure how much Eden cares about this -- but it will break qemu-system-aarch64 running EVE -- should we be concerned?

2021-02-09 17:43 UTC, giggsoff commented on pkg/defaults/defaults.go
> +	DefaultQemuAccelLinux  = "-cpu host "
Actually, this part of code is outdated, as I see

2021-02-13 21:44 UTC, merged

2021-02-13 21:44 UTC, mydatascience commented
ok let's merge and then I fix yetus